# Generated by Django 3.1.4 on 2021-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformationmodel',
            name='farmernum',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='fisheries',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='fivehundred_to_1000',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='goat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='income',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='innov_method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='more4000',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='one_to_fivehundred',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='one_two_thousand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='others',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='poultry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='prodCompany',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='surplus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='two_four_thousand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='vegetable',
            field=models.CharField(default='', max_length=50),
        ),
    ]
