# Generated by Django 3.1.4 on 2021-06-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210611_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='farmernum',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='fisheries',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='goat',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='income',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='innov_method',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='others',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='poultry',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='prodCompany',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='surplus',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='vegetable',
        ),
    ]
