# Generated by Django 3.1.4 on 2021-06-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20210611_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='more4000',
        ),
    ]
