# Generated by Django 3.1.4 on 2021-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_basicinformationmodel_more4000'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformationmodel',
            name='innov_method',
            field=models.CharField(default='', max_length=50),
        ),
    ]
