# Generated by Django 3.1.4 on 2021-06-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_basicinformationmodel_innov_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='fivehundred_to_1000',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='one_to_fivehundred',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='one_two_thousand',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='two_four_thousand',
        ),
    ]
