# Generated by Django 3.1.4 on 2021-06-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210611_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='innov_method',
        ),
    ]
