# Generated by Django 3.1.4 on 2021-06-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_basicinformationmodel_innov_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformationmodel',
            name='fivehundred_to_1000',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='more4000',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='one_to_fivehundred',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='one_two_thousand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='two_four_thousand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
