# Generated by Django 3.1.4 on 2021-06-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20210611_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='innov_method',
            field=models.CharField(default='', max_length=150),
        ),
    ]
