# Generated by Django 3.1.4 on 2021-06-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20210611_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='averagehousehold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='covervillage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='lng',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='shg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
