# Generated by Django 3.1.4 on 2021-06-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20210612_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='lat',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='lng',
            field=models.CharField(default='', max_length=15),
        ),
    ]
