# Generated by Django 3.1.4 on 2021-06-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20210612_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='averagehousehold',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='covervillage',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='shg',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
