# Generated by Django 3.1.4 on 2021-06-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_auto_20210612_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='fisheries',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='fivehundred_to_1000',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='goat',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='more4000',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='one_to_fivehundred',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='one_two_thousand',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='others',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='poultry',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='two_four_thousand',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='vegetable',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
    ]
