# Generated by Django 3.1.4 on 2021-05-04 17:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210430_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespage',
            name='content',
            field=wagtail.core.fields.StreamField([('videocards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('caption', wagtail.core.blocks.CharBlock(help_text='Caption', required=True)), ('video', wagtail.embeds.blocks.EmbedBlock(label='Video'))])))])), ('articlecards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('author', wagtail.core.blocks.CharBlock(help_text='Author', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Description', required=True)), ('article', wagtail.core.blocks.RichTextBlock(help_text='Article', required=True))])))])), ('weblinkcards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Description', required=True)), ('article', wagtail.core.blocks.RichTextBlock(help_text='link', required=True))])))]))], blank=True, null=True),
        ),
    ]
